import requests
from bs4 import BeautifulSoup
import re
import sys
from webpage import list


class GetText():

    def __init__(self, text):
        self.text = text

    def splitToWord(self):
        '''
        input: list generated by "getAlltext" function
    
        output: splits each word from the text apart and returns as list
        '''
        words = []
        for text in self.text:
            for word in text.split(" "):
                words.append(word)
        return words

    def standarizeWords(self):
        '''
        input: list [strings]
    
        deletes all the string containing a number,
        removes any punctuation from each string,
    
        output: list [strings]
        '''
        new_word_list = []
        numbers = ["0","1","2","3","4","5","6","7","8","9"]
        p = re.compile("(\.|\!|\,|\?|\:|\;|\)|\(|\\|\/|\'|\")")
        for word in self.text:
            is_word = True
            word = p.sub(" ", word)
            word = word.lower()
            for number in numbers:
                if number in word:
                    is_word = False
                    break
            if is_word == True:
                new_word_list.append(word)
            new_word_list.sort()
        return new_word_list

    def countWords(self):
        '''
        input: list [strings]
            
        counts number of appearances of each word in the list
    
        output: dictionary { word : count of appearances }
        '''
        words_count = {}
        for word in self.text:
            if word in words_count:
                words_count[word] += 1
            else:
                words_count[word] = 1
        return words_count

    def top5words(self):
        '''
        input: dictionary genereted by "countWords" function
    
        output: list of 5 keys(words) with biggest value
    
        NOT FULLY FUNCTIONAL
        '''
        words = self.countWords()
        top_num = 0
        top_word = ""
        keys = words.keys()
        for key in keys:
            if len(key) > 3 and key != 'the':  # banned words
                if words[key] > top_num:
                    top_num = words[key]
                    top_word = key
        return top_word



    # def collect_words():
    #     '''
    #     input: address of existing website
    #
    #     returns tuple (domain name, dictionary { words on site : number of appearences })
    #     '''
    #     words = standarizeWords(splitToWord(getAlltext(address)))
    #
    #     return words

#siema = GetText(list).top5words()
#print(siema)